/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Engine.java
 *
 * Created on 22 Jun, 2011, 2:09:51 PM
 */

package com.wishtrack.jgge.engine;

import javax.swing.JFrame;

/**
 *
 * @author Administrator
 */
public class Engine extends javax.swing.JFrame {

    
    /** Creates new form Engine */
    public Engine() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        spritesPanel = new javax.swing.JPanel();
        propertiesPanel = new javax.swing.JPanel();
        previewPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        preview = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newProject = new javax.swing.JMenuItem();
        openProject = new javax.swing.JMenuItem();
        saveProject = new javax.swing.JMenuItem();
        openEditor = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        spritesMenu = new javax.swing.JMenu();
        createSprite = new javax.swing.JMenuItem();
        deleteSprite = new javax.swing.JMenuItem();
        editSprite = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java GUI Game Engine");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(0, 0, 1366, 750));
        setMinimumSize(new java.awt.Dimension(600, 400));

        listPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        listPanel.setLayout(new java.awt.GridLayout(2, 0));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jPanel4, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jPanel4, org.jdesktop.beansbinding.BeanProperty.create("autoscrolls"));
        bindingGroup.addBinding(binding);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sprites");
        jPanel4.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        spritesPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout spritesPanelLayout = new javax.swing.GroupLayout(spritesPanel);
        spritesPanel.setLayout(spritesPanelLayout);
        spritesPanelLayout.setHorizontalGroup(
            spritesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );
        spritesPanelLayout.setVerticalGroup(
            spritesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );

        jPanel4.add(spritesPanel, java.awt.BorderLayout.CENTER);

        listPanel.add(jPanel4);

        propertiesPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout propertiesPanelLayout = new javax.swing.GroupLayout(propertiesPanel);
        propertiesPanel.setLayout(propertiesPanelLayout);
        propertiesPanelLayout.setHorizontalGroup(
            propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );
        propertiesPanelLayout.setVerticalGroup(
            propertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        listPanel.add(propertiesPanel);

        getContentPane().add(listPanel, java.awt.BorderLayout.LINE_START);

        previewPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        previewPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Preview");
        previewPanel.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        preview.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout previewLayout = new javax.swing.GroupLayout(preview);
        preview.setLayout(previewLayout);
        previewLayout.setHorizontalGroup(
            previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1026, Short.MAX_VALUE)
        );
        previewLayout.setVerticalGroup(
            previewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );

        previewPanel.add(preview, java.awt.BorderLayout.CENTER);

        getContentPane().add(previewPanel, java.awt.BorderLayout.CENTER);

        fileMenu.setText("File");

        newProject.setText("New Project");
        newProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProjectActionPerformed(evt);
            }
        });
        fileMenu.add(newProject);

        openProject.setText("Open Project");
        openProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openProjectActionPerformed(evt);
            }
        });
        fileMenu.add(openProject);

        saveProject.setText("Save project");
        saveProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProjectActionPerformed(evt);
            }
        });
        fileMenu.add(saveProject);

        openEditor.setText("Launch Editor");
        openEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openEditorActionPerformed(evt);
            }
        });
        fileMenu.add(openEditor);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        fileMenu.add(exit);

        jMenuBar1.add(fileMenu);

        spritesMenu.setText("Sprites");

        createSprite.setText("Create New Sprite");
        createSprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSpriteActionPerformed(evt);
            }
        });
        spritesMenu.add(createSprite);

        deleteSprite.setText("Delete a Sprite");
        deleteSprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSpriteActionPerformed(evt);
            }
        });
        spritesMenu.add(deleteSprite);

        editSprite.setText("Edit a Sprite");
        editSprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSpriteActionPerformed(evt);
            }
        });
        spritesMenu.add(editSprite);

        jMenuBar1.add(spritesMenu);

        setJMenuBar(jMenuBar1);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void newProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProjectActionPerformed
        // TODO add your handling code here: Add Code to create a new Project
    }//GEN-LAST:event_newProjectActionPerformed

    private void openProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openProjectActionPerformed
        // TODO add your handling code here: Add Code to open an existing project
    }//GEN-LAST:event_openProjectActionPerformed

    private void saveProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProjectActionPerformed
        // TODO add your handling code here: Add Code to save current project
    }//GEN-LAST:event_saveProjectActionPerformed

    private void openEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openEditorActionPerformed
        // TODO add your handling code here: Add code to open the Editor
    }//GEN-LAST:event_openEditorActionPerformed

    private void createSpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSpriteActionPerformed
        // TODO add your handling code here: Add code to create a new Sprite
    }//GEN-LAST:event_createSpriteActionPerformed

    private void deleteSpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSpriteActionPerformed
        // TODO add your handling code here: Add code to delete a sprite
    }//GEN-LAST:event_deleteSpriteActionPerformed

    private void editSpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSpriteActionPerformed
        // TODO add your handling code here: Add Code to  edit current Sprites
    }//GEN-LAST:event_editSpriteActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Engine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem createSprite;
    private javax.swing.JMenuItem deleteSprite;
    private javax.swing.JMenuItem editSprite;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel listPanel;
    private javax.swing.JMenuItem newProject;
    private javax.swing.JMenuItem openEditor;
    private javax.swing.JMenuItem openProject;
    private javax.swing.JPanel preview;
    private javax.swing.JPanel previewPanel;
    private javax.swing.JPanel propertiesPanel;
    private javax.swing.JMenuItem saveProject;
    private javax.swing.JMenu spritesMenu;
    private javax.swing.JPanel spritesPanel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public static void main() {
        new Engine().setVisible(true);
    }
}
